version: '3'
services:
  db:
    image: postgres:12.1
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data
    env_file:
      - envs/wishlist.env

  backend:
    image: wishlist/backend
    build:
      context: ./backend
      dockerfile: backend.Dockerfile
    ports:
      - "8080"
    volumes:
      - ./backend:/app
      - media:/media
    env_file:
      - envs/wishlist.env
    command: >
      bash -c "
       ./manage.py migrate
       ./manage.py runserver 0.0.0.0:8080
      "
    links:
      - db
      - backend_worker

  backend_worker:
    image: wishlist/backend
    volumes:
      - ./backend:/app
    env_file:
      - envs/wishlist.env
    depends_on:
      - broker
    command: >
      bash -c "
      celery worker --beat --app=wishlist_backend.celery_app --concurrency=4 --hostname=backend_worker@%h --loglevel=INFO
      "

  front:
    image: wishlist/front
    build:
      context: ./front
      dockerfile: front.Dockerfile
    ports:
      - "3000"
    volumes:
      - ./front/wishlist_front:/app
    env_file:
      - envs/wishlist.env
    links:
      - backend
    command: >
      bash -c "
        yarn &&
        yarn start
      "

  broker:
    image: rabbitmq:3.8
    env_file:
      - envs/wishlist.env
    ports:
      - 5672:5672

  proxy:
    image: nginx:latest
    depends_on:
      - front
      - backend
    expose:
      - "8080"
      - "3000"
    ports:
      - "8080:8080"
      - "3000:3000"
    volumes:
      - ./nginx/nginx.default.conf:/etc/nginx/conf.d/web.conf
      - media:/media

volumes:
  pgdata:
  media:

